### PR TITLE
chore: bump stacks-core and run tests

### PR DESCRIPTION
**Pull request by cylewitruk**
## Description

Closes: #612 

Bumps `stacks-core`, `clarity` and `stacks-common` to commit hash `c87c0eb6c050688340b975b0b42fb0a1ae378afa` (most recent from `develop`).

## Changes

Just dependency version.

## Testing Information

Nothing special, all existing tests pass.

## Checklist:

- [x] I have performed a self-review of my code
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by djordon — APPROVED** [review]
🚀 🚢 ✅

**Comment by djordon** [comment]
@cylewitruk have you tried running the stacks integration tests with a locally running nakamoto stacks-core? The existing tests do not test against stacks-core in CI, since it isn't hooked up.

**Comment by cylewitruk** [comment]
@djordon are you referring to the tests marked with `#[ignore = "This is an integration test that hasn't been setup for CI yet"]`?

**Comment by djordon** [comment]
yes

**Comment by cylewitruk** [comment]
It was a pain to test, but I finally confirmed them all working against `devenv` with the same stacks node version. Merging now

**Pull request merged**
